### ISSUE TITLE
rEFInd was not default boot option

### ISSUE THREAD

**Issue by ghost** [DeckWizard/steamdeck_dualboot#3]
After installing both Steam OS and Windows 10 respectively, I installed rEFInd just for Windows 10 to remain the default boot option upon install so I was wondering if there was a way to fix this.

I have tried to reinstall it but it didn't work.

**Comment by code0344** [comment]
Same here. Have you resolve it already? Please tell me what did you do

**Comment by tegaidogun** [comment]
Yeah disable Windows 10 Boot option using `efibootmgr`. Check the Windows boot option number using the command:

`sudo efibootmgr` 

and you get number `XXXX`. Then use the command: `sudo efibootmgr -b XXXX -A` to disable it

if you want to re-enable it use `sudo efibootmgr -b XXXX -a`.


If it says the boot option doesn't exist, you'll need to use a bootable USB, preferably the SteamOS 3 Recovery image and re-run these commands.
